### ISSUE TITLE
Muy bien!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-claradios#1]
Buen trabajo @claradios  !

Dos cositas para fetenearlo del to:

- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by claradios** [comment]
Hola @oneeyedman !
Ya hice las mejoras.
Saludos

**Comment by oneeyedman** [comment]
Estupendo!
